name: on-push-actions-setup-python
on:
  push

jobs:
  python:
    runs-on: ubuntu-20.04
    steps:
      - run: |
          which python
          python --version
      - run: |
          which python3
          python3 --version
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8.1'
      - run: |
          which python
          python --version
      - run: |
          which python3
          python3 --version

